[profile.default]
src = 'contracts'
out = 'out'
# libs = ['lib']
libs = ['node_modules', 'lib']
test = 'tests/foundry'
cache_path = 'forge-cache'
ffi = true
fs_permissions = [
  { access = "read", path = "./artifacts/" },
  { access = "read-write", path = "./.forge-snapshots/" },
]

# Pins the block number for the state fork
# fork_block_number = 16437883

# block_timestamp = 1651743369 # Arbitrary Thursday, 5 May 2022 09:36:09
verbosity = 3
# check version in .prettierrc.json when changing this
solc_version = '0.8.28'
auto_detect_solc = false
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200

block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 0
block_timestamp = 0
cache = true
force = false
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
# ignore solc warnings for missing license and exceeded contract size
# known error codes are: ["unreachable", "unused-return", "unused-param", "unused-var", "code-size", "shadowing", "func-mutability", "license", "pragma-solidity", "virtual-interfaces", "same-varname"]
# additional warnings can be added using their numeric error code: ["license", 1337]
# ignored_error_codes = ["license", "code-size"]
initial_balance = '0xffffffffffffffffffffffff'
# just add this for mainnet
# libraries = ["contracts/core/lib/FXPoolDeployerLib.sol:FXPoolDeployerLib:0xCb0b358cF6133aA55B5E4483aD0F4dE511590C77"] 
libraries = []
offline = false

### Just add --sender in the command when deploying
# sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
# tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'


[fuzz]
runs = 256
max_test_rejects = 524288

# create a CI profile
[profile.ci]
runs = 2560
